### ISSUE TITLE
Should cmdParts remove empty strings?

### ISSUE THREAD

**Issue by zzctmac** [amalfra/oexec#2]
The [line](https://github.com/amalfra/oexec/blob/main/oexec.go#L48) splits cmd string to parts. But some of these parts could be empty. So is it proper to remove empty strings?

**Comment by amalfra** [comment]
@zzctmac Nice catch! That cleanup before sending to exec would be a safeguard. Please feel free to raise a PR if you want to or else I can fix it this weekend.

**Comment by zzctmac** [comment]
Thanks for your reply. It would be great if you can fix it.

**Comment by amalfra** [comment]
@zzctmac This is fixed and available in the latest release!
